/*
INSERT INTO concejos (denom) VALUES ('Avilés');
INSERT INTO concejos (denom) VALUES ('Candamo');
INSERT INTO concejos (denom) VALUES ('Castrillón');
INSERT INTO concejos (denom) VALUES ('Corvera');
INSERT INTO concejos (denom) VALUES ('Cudillero');
INSERT INTO concejos (denom) VALUES ('Gozón');
INSERT INTO concejos (denom) VALUES ('Illas');
INSERT INTO concejos (denom) VALUES ('Muros de Nalón');
INSERT INTO concejos (denom) VALUES ('Pravia');
INSERT INTO concejos (denom) VALUES ('Aller');
INSERT INTO concejos (denom) VALUES ('Lena');
INSERT INTO concejos (denom) VALUES ('Mieres');
INSERT INTO concejos (denom) VALUES ('Boal');
INSERT INTO concejos (denom) VALUES ('Castropol');
INSERT INTO concejos (denom) VALUES ('Coaña');
INSERT INTO concejos (denom) VALUES ('El Franco');
INSERT INTO concejos (denom) VALUES ('Grandas de Salime');
INSERT INTO concejos (denom) VALUES ('Illano');
INSERT INTO concejos (denom) VALUES ('Navia');
INSERT INTO concejos (denom) VALUES ('Pesoz');
INSERT INTO concejos (denom) VALUES ('San Martín de Oscos');
INSERT INTO concejos (denom) VALUES ('San Tirso de Abres');
INSERT INTO concejos (denom) VALUES ('Santa Eulalia de Oscos');
INSERT INTO concejos (denom) VALUES ('Tapia de Casariego');
INSERT INTO concejos (denom) VALUES ('Taramundi');
INSERT INTO concejos (denom) VALUES ('Valdés');
INSERT INTO concejos (denom) VALUES ('Vegadeo');
INSERT INTO concejos (denom) VALUES ('Villanueva de Oscos');
INSERT INTO concejos (denom) VALUES ('Villayón');
INSERT INTO concejos (denom) VALUES ('Carreño');
INSERT INTO concejos (denom) VALUES ('Gijón');
INSERT INTO concejos (denom) VALUES ('Villaviciosa');
INSERT INTO concejos (denom) VALUES ('Caso');
INSERT INTO concejos (denom) VALUES ('Langreo');
INSERT INTO concejos (denom) VALUES ('Laviana');
INSERT INTO concejos (denom) VALUES ('San Martín del Rey Aurelio');
INSERT INTO concejos (denom) VALUES ('Sobrescobio');
INSERT INTO concejos (denom) VALUES ('Allande');
INSERT INTO concejos (denom) VALUES ('Cangas del Narcea');
INSERT INTO concejos (denom) VALUES ('Ibias');
INSERT INTO concejos (denom) VALUES ('Tineo');
INSERT INTO concejos (denom) VALUES ('Amieva');
INSERT INTO concejos (denom) VALUES ('Cabrales');
INSERT INTO concejos (denom) VALUES ('Cangas de Onís');
INSERT INTO concejos (denom) VALUES ('Caravia');
INSERT INTO concejos (denom) VALUES ('Colunga');
INSERT INTO concejos (denom) VALUES ('Llanes');
INSERT INTO concejos (denom) VALUES ('Onís');
INSERT INTO concejos (denom) VALUES ('Parres');
INSERT INTO concejos (denom) VALUES ('Peñamellera Alta');
INSERT INTO concejos (denom) VALUES ('Peñamellera Baja');
INSERT INTO concejos (denom) VALUES ('Piloña');
INSERT INTO concejos (denom) VALUES ('Ponga');
INSERT INTO concejos (denom) VALUES ('Ribadedeva');
INSERT INTO concejos (denom) VALUES ('Ribadesella');
INSERT INTO concejos (denom) VALUES ('Belmonte de Miranda');
INSERT INTO concejos (denom) VALUES ('Bimenes');
INSERT INTO concejos (denom) VALUES ('Cabranes');
INSERT INTO concejos (denom) VALUES ('Grado');
INSERT INTO concejos (denom) VALUES ('Llanera');
INSERT INTO concejos (denom) VALUES ('Morcín');
INSERT INTO concejos (denom) VALUES ('Nava');
INSERT INTO concejos (denom) VALUES ('Noreña');
INSERT INTO concejos (denom) VALUES ('Oviedo');
INSERT INTO concejos (denom) VALUES ('Proaza');
INSERT INTO concejos (denom) VALUES ('Quirós');
INSERT INTO concejos (denom) VALUES ('Las Regueras');
INSERT INTO concejos (denom) VALUES ('Ribera de Arriba');
INSERT INTO concejos (denom) VALUES ('Riosa');
INSERT INTO concejos (denom) VALUES ('Salas');
INSERT INTO concejos (denom) VALUES ('Sariego');
INSERT INTO concejos (denom) VALUES ('Siero');
INSERT INTO concejos (denom) VALUES ('Somiedo');
INSERT INTO concejos (denom) VALUES ('Teverga');
INSERT INTO concejos (denom) VALUES ('Yernes y Tameza');



INSERT INTO concejoscomarcas (idcomarca,idconcejo) VALUES (1,1);
INSERT INTO concejoscomarcas (idcomarca,idconcejo) VALUES (1,2);
INSERT INTO concejoscomarcas (idcomarca,idconcejo) VALUES (1,3);
INSERT INTO concejoscomarcas (idcomarca,idconcejo) VALUES (1,4);
INSERT INTO concejoscomarcas (idcomarca,idconcejo) VALUES (1,5);
INSERT INTO concejoscomarcas (idcomarca,idconcejo) VALUES (1,6);
INSERT INTO concejoscomarcas (idcomarca,idconcejo) VALUES (1,7);
INSERT INTO concejoscomarcas (idcomarca,idconcejo) VALUES (1,8);
INSERT INTO concejoscomarcas (idcomarca,idconcejo) VALUES (1,9);
*/

INSERT INTO concejoscomarcas (idcomarca,idconcejo) VALUES (2,10);
INSERT INTO concejoscomarcas (idcomarca,idconcejo) VALUES (2,11);
INSERT INTO concejoscomarcas (idcomarca,idconcejo) VALUES (2,12);

INSERT INTO concejoscomarcas (idcomarca,idconcejo) VALUES (3,13);
INSERT INTO concejoscomarcas (idcomarca,idconcejo) VALUES (3,14);
INSERT INTO concejoscomarcas (idcomarca,idconcejo) VALUES (3,15);
INSERT INTO concejoscomarcas (idcomarca,idconcejo) VALUES (3,16);
INSERT INTO concejoscomarcas (idcomarca,idconcejo) VALUES (3,17);
INSERT INTO concejoscomarcas (idcomarca,idconcejo) VALUES (3,18);
INSERT INTO concejoscomarcas (idcomarca,idconcejo) VALUES (3,19);
INSERT INTO concejoscomarcas (idcomarca,idconcejo) VALUES (3,20);
INSERT INTO concejoscomarcas (idcomarca,idconcejo) VALUES (3,21);
INSERT INTO concejoscomarcas (idcomarca,idconcejo) VALUES (3,22);
INSERT INTO concejoscomarcas (idcomarca,idconcejo) VALUES (3,23);
INSERT INTO concejoscomarcas (idcomarca,idconcejo) VALUES (3,24);
INSERT INTO concejoscomarcas (idcomarca,idconcejo) VALUES (3,25);
INSERT INTO concejoscomarcas (idcomarca,idconcejo) VALUES (3,26);
INSERT INTO concejoscomarcas (idcomarca,idconcejo) VALUES (3,27);
INSERT INTO concejoscomarcas (idcomarca,idconcejo) VALUES (3,28);
INSERT INTO concejoscomarcas (idcomarca,idconcejo) VALUES (3,29);
